---
- name: Check if profile file exists
  ansible.builtin.stat:
    path: /etc/profile.d/horizon-cli-path.sh
  register: profile

- name: Cleanup profile file
  ansible.builtin.file:
    path: "{{ profile.stat.path }}"
    state: absent
  when: profile.stat.exists

- name: Check if fact file exists
  ansible.builtin.stat:
    path: /etc/ansible/facts.d/horizon-cli.fact
  register: fact

- name: Cleanup fact file
  ansible.builtin.file:
    path: "{{ fact.stat.path }}"
    state: absent
  when: fact.stat.exists